### ISSUE TITLE
recostruction issue using PaCER on Lead-DBS

### ISSUE THREAD

**Issue by ariannafelice** [adhusch/PaCER#18] opened 2019-01-24 10:34 UTC
Dear all,
i'm using PaCER inside the toolbox matlab Lead-DBS. I usually work on CT scan, the pipe line seems to work, but I’ve run into difficulties with the recostruction steps. I got this error 

Error using ea_reconstruct_trajectory (line 282)
Mask out of bounds! Must have lost trajectory...
Please try a different 'Mask window size' or try manual mode by setting 'Entrypoint for Target' to
'Manual'.

 Error while evaluating UIControl Callback.

Can somebody help me?
Thanks in advace for your collaboration.
Regards,
Arianna

**Comment by adhusch** [comment] 2019-01-24 10:56
Hi Arianna,

the error 

_Please try a different 'Mask window size' or try manual mode by setting 'Entrypoint for Target' to
'Manual'._ 

is actually NOT a PaCER error but an error from the legacy "Trac/Core" algorithm. LeadDBS might revert to that one if PaCER fails. If this is the case could you try to find the original PaCER error message and post these?

Thank
Best
Andreas

**Comment by ariannafelice** [comment] 2019-01-24 11:35
Maybe this one:

Warning: PaCER failed with the following error: 
> In ea_autocoord (line 270)
  In ea_run (line 96)
  In lead_dbs>run_button_Callback (line 187)
  In gui_mainfcn (line 95)
  In lead_dbs (line 43)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)lead_dbs('run_button_Callback',hObject,eventdata,guidata(hObject)) 
Identifier: 
Message: PaCER returned a different number of electrodes than expected by LeadDBS! In most cases this indicates an error in PaCER preprocessing (brain mask estimation) due to untypical CT data. Please provide a brain mask to PaCER in this case using the mask parameter.
In: C:\Users\BIOING\Desktop\STUDI\lead\ea_runpacer.m
Method: ea_runpacer
Line: 17
Please check your input data carefully.

**Comment by adhusch** [comment] 2019-02-04 11:55
Hi!
Sorry for the delayed reply. I will come back to you next week. Could you text me on the leadusers slack channel?
Best

**Comment by adhusch** [comment] 2019-02-07 07:01
Duplicate of  #19

**Closed as completed by adhusch** 2019-02-07 07:02 UTC
Labels: wontfix, LeadDBS
